# Generated by Django 3.0.5 on 2024-05-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
